In [1]:
import pandas as pd
import numpy as np
from gspread_pandas import Spread,Client
import selenium
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
import time
import datetime
import warnings
warnings.filterwarnings("ignore")
from selenium.webdriver.common.by import By
from selenium.common.exceptions import NoSuchElementException

my_credentials = {
 "type": "service_account",
  "project_id": "crafty-plateau-328717",
  "private_key_id": "4afdb5a0906054d2d69cd46b2e8af41b73b9b8a7",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDcQv0qyESqHiYz\n82V5rSDiEG8xMGF0hIC9cJirwrDgAhEpjKIQRnJ227g6CP/8CTYYSrvJXmGzTZrB\n+FtrYWeZPjuIZGPyPJShIG//4LWcjlnh/h5zilKcmyaKsu5M0BSWiW0rkIUwYFgS\nox6xfiW3UbYWIUAGVvwDBYopUExaEV/a9l8p43pKDXHmZfq4ZIu2XgLDqalDLbCW\n1FjU7umMWS9KEvibo6mUkia9kkw1DvEsIkbWny3Bm0SoDLeqG0B6OsXhOYMfEJ+W\nSR80TR4Fu+EVfzRocwNVQHOKB2o0mbd/0AA1z/OPGM99QJXXKm8+CdV0KTbj6MUB\ns2/YTlG5AgMBAAECggEAKJ8IHrhBhZg61nDogYiu3FJIl2tDReBb99QIrACjaySm\ncqG3j8XWPVpnPvjC8QHn4pIB0PDhltZUmLpLbeHQX+AszYoqLpYCmTaowSl5hO5x\n4C5kAk37z1sDwCegsDTd3ydoJVUpYxMZmxJPSk+n+AePS8SFEMZBAvOmF9lxw1hC\nJoYkw4/H9XvuW7fTiOK2le6GokWgDUqSgTQRHO78NION1Z5pB5ymAKrV7w5GH4LI\nkFIuOxQEHhLv0a2URVEzkHX3VGPbBHF4MQ/Z8ObxqEsefkOnEpRIRTsE8+G44coB\nYbVdhe0132qgotEN1GvsBLwq+TJIknt38jkDcs9sKwKBgQD+sGqDtvCzSz5rk/Xg\nNHFOq9FsWSeUuw9jxw4XJxVqYbJbLcy0DmfIPg1rZgPW8X+6upt5RigHVBixqz74\nsnP9IvmVuoU6s9VoW1HaYbnbg5Zqp3WFa6xHZv/vXIapfCX8binEsVWwYW2gb2AJ\nE13jFJWZB7n8zatEk9ho1Rv50wKBgQDdZTXjsc0N3DZhCR39zPGr811VBmnXuUwW\nG1MG7z4npe2eFeTYHepKN8c3Ot+boyDm+K+NsEYHLH6wlcXFxMHAgSY6xAe8k+4i\n8EgwgUPfmawUrv7tXsAhASZNJwoE4S9S/kY/WFJR6CddaMUYvNtle5P99D//uoGG\nXcJWdEsiwwKBgQDBNaoIM98T1RAMYlmTdZVDfjrIPDY3sVSyd85rp/2qD2VToEH7\nkjYPBWv+voxJIjmouWm6rYsuTBDTr7p8xjwRm9fFS5NIfiZ2HVjSF3L8YS3ZySHx\nTkaKgEvGFOYfawwSHKxZB8KepLqajANJv0RpQTNfvSnN62RzCMmSdaDcewKBgQC8\nKuprdNHYRuL9BDe2X7rDr5sSydmpnPa7D0w455wHLLLRmsAeowZfQBsUqPgmGra7\nOIBUx44tSLcAtLscBMe8KshoR/ZfY8eRcHGasDMU11J3XeiTrOVU59o61sRgM1f6\njNz9t753mP3kGUjzZoh+L1MwE6lVW5n8rrGes0as6wKBgE54ZYZcUXRbOh+d1I9e\njWfwqr/mfvVGUZIBP4qDgL4dNHPWzWT7gjZIQUWJyXIMjP+04dly5ugJIX5UEC1M\nWPH1f9nsW3tvSp5suycEvtyXqEqrudLTHPOKhFWFDdh1bpO6y6GuAXMBU7FywTgi\n49Cl8Nil36anL8yJHhf7RSOF\n-----END PRIVATE KEY-----\n",
  "client_email": "aakashgooglesheets@crafty-plateau-328717.iam.gserviceaccount.com",
  "client_id": "108448941747378112883",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/aakashgooglesheets%40crafty-plateau-328717.iam.gserviceaccount.com"
}

In [2]:
while True:
    try:
        spread = Spread('GIF_2025_Mapping_Requirement',config=my_credentials)        ##  worksheet_name
        sheet = spread.open_sheet("Amaozon_Buybox")                                        ##sheet_name
        asins_sheet = spread.sheet_to_df(sheet=sheet,index=0)
        asins_sheet.head()
        break
    except Exception as e:
        print(f"An error occurred: {e}")
        print('Retrying')

In [ ]:
# asins_sheet.head()

,asin,account,category,sub_category,sub_category_1,sub_category_2,sub_category_3
0,B07G1C4YF2,Jockey,Panties,JJ - IW,SG01,,
1,B07G1G4VCB,Jockey,Panties,JJ - IW,SG01,,
2,B07G1C4XK7,Jockey,Panties,JJ - IW,SG01,,
3,B07G1H1PD5,Jockey,Panties,JJ - IW,SG03,,
4,B07G1KRYX2,Jockey,Panties,JJ - IW,SG03,,

In [4]:
asins_list = asins_sheet[asins_sheet['asin']!=""]['asin'].to_list()
len(asins_list)

6597

In [5]:
# Amazon_buybox_prime_25
# asins_list=asins_list[:220]               # Rohit
# asins_list=asins_list[220:440]            # Ajay
# asins_list=asins_list[440:660]           # Koushik
# asins_list=asins_list[660:880]          # Surya
# asins_list=asins_list[880:1100]          # shruthi
# asins_list=asins_list[1100:1320]          # jibin
# asins_list=asins_list[1320:1540]          # karnakaran
# asins_list=asins_list[1540:1760]           # Hemanth
# asins_list=asins_list[1760:1980]           # sumit
# asins_list=asins_list[1980:2200]           # Harish
# asins_list=asins_list[2200:2420]           # Hari Prasad
# asins_list=asins_list[2420:2640]           # Rishab
# asins_list=asins_list[2640:]                # Rajshekhar

In [6]:
pincodes=['110001','400001','560001','500001','700001']

In [7]:
asins_list=asins_list[0:100]

In [8]:
len(asins_list)

100

In [9]:
browser = webdriver.Chrome() #r"C:\Users\hmlt0\Downloads\Applications\chromedriver-win32\chromedriver.exe"

In [10]:
browser.get('https://www.amazon.in')

In [11]:
%%time
iterations = len(asins_list) * len(pincodes)
asin = []
title = []
stock = []
seller = []
pin_df = []
buybox = []
bsr = []
price = []
mrp = []
free_delivery = []
fast_delivery = []
fresh_avail=[]
fresh_price=[]
fresh_seller=[]
star_rating=[]
no_of_rating=[]
current_hours=[]
try:
    url = "https://www.amazon.in/s?k=wow&crid=1LZA2DRTNJY7B&sprefix=wow%2Caps%2C235&ref=nb_sb_noss_1"
    browser.get(url)
    time.sleep(2)

    for pin in pincodes:
        print("Processing pincode:", pin)

        try:
            # Set the pincode in the browser
            try:
                browser.find_element(By.CSS_SELECTOR, "#glow-ingress-line2").click()
                time.sleep(2)
            except:
                browser.get("https://www.amazon.in")
                browser.find_element(By.ID, "nav-global-location-popover-link").click()
                time.sleep(2)

            browser.find_element(By.CSS_SELECTOR, "#GLUXZipUpdateInput").clear()
            time.sleep(2)
            browser.find_element(By.CSS_SELECTOR, "#GLUXZipUpdateInput").send_keys(pin)
            time.sleep(2)
            browser.find_element(By.CSS_SELECTOR, "#GLUXZipUpdate > span > input").click()
            time.sleep(2)
            print("Pincode Entry Success")

            for i in asins_list:
                try:
                    browser.get("https://www.amazon.in/dp/{}/".format(i))
                except:
                    pass

                try:
                    asin.append(i)
                except:
                    asin.append("None")
                try:
                    title.append(browser.find_element(By.CSS_SELECTOR,"#productTitle").text)
                except:
                    title.append("None")
                try:
                    if browser.find_element(By.ID,'buy-now-button').click:
                        buybox.append("Yes")
        
                except:
                    try:
                        browser.find_element(By.XPATH,'//*[@id="unqualifiedBuyBox"]/div/div[2]').click()
                        time.sleep(2)
                        seller_name = ""
                        try:
                            for i in browser.find_element(By.XPATH,'//*[@id="aod-offer-soldBy"]/div/div/div[2]/a'):
                                seller_name+=" & "+i.text
                        except:
                            seller_name = "No"
                        buybox.append(seller_name)
                    except:
                        buybox.append("No")
                try:
                    stock.append(browser.find_element(By.CSS_SELECTOR,"#availability").text)
                except:
                    try:
                        stock.append(browser.find_element(By.CSS_SELECTOR,"#freshAddToCartButton > span").text)
                    except:
                        stock.append("None")
                try:
                    seller.append(browser.find_element(By.CSS_SELECTOR,"#sellerProfileTriggerId").text)                        
                except:
                    try:
                        seller.append(browser.find_element(By.CSS_SELECTOR,"#sellerProfileTriggerId").text)
                    except:
                        try:
                            seller.append(browser.find_element(By.CSS_SELECTOR,"#merchant-info > a:nth-child(2) > span").text)
                        except:
                            try:
                                seller.append(browser.find_element(By.CSS_SELECTOR,'#freshShipsFromSoldBy_feature_div > div > table > tbody > tr:nth-child(1) > td:nth-child(2)').text)
                            except:
                                seller.append("None")
                if seller[-1]=='abc':
                    browser.maximize_window()
                    browser.save_screenshot()
                    print('Screenshot saved')
                try:
                    pin_df.append(pin)
                except:
                    pin_df.append("None")

                try:
                    bsr.append(browser.find_element(By.XPATH,'//*[@id="detailBulletsWrapper_feature_div"]').text.split("Best Sellers Rank:")[1].split("\nCustomer Reviews:")[0])
                except:
                    try:
                        bsr.append(browser.find_element(By.XPATH,'//*[@id="productDetails_db_sections"]').text.split("Best Sellers Rank")[1].split("Date First Available")[0])
                    except:
                        bsr.append("None")    


                try:
                    price.append(soup.find('span', {'class': "a-price aok-align-center reinventPricePriceToPayMargin priceToPay"}).text.split('₹')[1])
                    
                except:
                    try:
                        price.append(soup.find('span', {'class': "a-price a-text-price a-size-medium apexPriceToPay"}).text.split('₹')[1])
                    except:
                        try:
                            price.append(soup.find('span', {'class': "a-price-whole"}).text)
                        except:
                            try:
                                price.append(browser.find_element(By.XPATH,'//*[@id="corePriceDisplay_desktop_feature_div"]/div[1]/span[2]/span[2]/span[2]').text.replace('₹',''))
                            except:
                                try:
                                    price.append(browser.find_element(By.XPATH,'//*[@id="corePrice_desktop"]/div/table/tbody/tr[2]/td[2]/span[1]/span[2]').text.replace('₹',''))
                                except:
                                    try:
                                        price.append(browser.find_element(By.XPATH,'//*[@id="corePriceDisplay_desktop_feature_div"]/div[1]/span[1]/span[2]/span[2]').text.replace('₹',''))
                                    except:
                                        try:
                                            price.append(browser.find_element(By.CSS_SELECTOR,'#corePriceDisplay_desktop_feature_div > div.a-section.a-spacing-none.aok-align-center > span:nth-child(2) > span > span:nth-child(2) > span.a-price-whole').text)
                                        except:
                                            try:
                                                price.append(browser.find_element(By.CSS_SELECTOR,'#corePriceDisplay_desktop_feature_div > div.a-section.a-spacing-none.aok-align-center.aok-relative > span.a-price.aok-align-center.reinventPricePriceToPayMargin.priceToPay > span:nth-child(2) > span.a-price-whole').text)
                                            except:
                                                price.append('None')



                try:    
                    mrp.append(soup.find('span', {'class': "a-price a-text-price"}).text.split('₹')[1])
                except:
                    try:
                        mrp.append(soup.find('span', {'class': "a-price-whole"}).text)
                    except:
                        try:
                            mrp.append(browser.find_element(By.XPATH,'//*[@id="corePriceDisplay_desktop_feature_div"]/div[2]/span/span[1]/span/span[2]').text.replace('₹',''))
                        except:
                            try:
                                mrp.append(browser.find_element(By.XPATH,'//*[@id="corePrice_desktop"]/div/table/tbody/tr[1]/td[2]/span[1]/span[2]').text.replace('₹',''))
                            except:
                                try:
                                    mrp.append(browser.find_element(By.CSS_SELECTOR,'#corePriceDisplay_desktop_feature_div > div.a-section.a-spacing-small.aok-align-center > span > span.aok-relative > span > span > span:nth-child(2)').text.replace('₹',''))
                                except:
                                    mrp.append('None')



                try:
                    free_delivery.append(browser.find_element(By.CSS_SELECTOR,'#mir-layout-DELIVERY_BLOCK-slot-PRIMARY_DELIVERY_MESSAGE_LARGE > span > span').text.split(', ')[1])           
                except:
                    free_delivery.append('none')

                #####----------####

                target_image_url = "https://m.media-amazon.com/images/I/31Ip4aURUpL.png"
                try:
                    img_tag = browser.find_element(By.CSS_SELECTOR, f'img[src="{target_image_url}"]')
                    fresh_avail.append('Yes')
                
                except NoSuchElementException:
                    fresh_avail.append('NO')

                try:
                    fresh_price.append(browser.find_element(By.CSS_SELECTOR,'#corePrice_feature_div > div > div > span.a-text-normal > span > span:nth-child(2) > span.a-price-whole').text)
                except:  
                    fresh_price.append('none')

                try: 
                    fresh_seller.append(browser.find_element(By.CSS_SELECTOR,'#freshShipsFromSoldBy_feature_div > div > table > tbody > tr:nth-child(1) > td:nth-child(2)').text)           
                except:
                    try:
                        fresh_seller.append(browser.find_element(By.CSS_SELECTOR,'#fresh-merchant-info > table > tbody > tr:nth-child(2) > td:nth-child(2)').text)
                    except:
                        fresh_seller.append('None') 

                try:
                    fast_delivery.append(browser.find_element(By.CSS_SELECTOR,'#mir-layout-DELIVERY_BLOCK-slot-SECONDARY_DELIVERY_MESSAGE_LARGE').text.split(', ')[1].split('.')[0])
                except:  
                    fast_delivery.append('none')
                time.sleep(1)

                try:
                    star_rating.append(browser.find_element(By.CSS_SELECTOR,'#acrPopover > span.a-declarative > a > span').text)
                except:
                    star_rating.append('None')

                try:
                    no_of_rating.append(browser.find_element(By.CSS_SELECTOR,'#acrCustomerReviewText').text.replace('ratings',''))
                except:
                    no_of_rating.append('None')
                ## this is to append the actual hour when i scrapped for this asin
                current_hour = datetime.datetime.now().hour
                current_hours.append(current_hour)
                
                
                print(iterations,"ASINS Remaining", i,seller[-1],stock[-1],price[-1],mrp[-1],fresh_avail[-1],star_rating[-1],no_of_rating[-1],free_delivery[-1])
                iterations-=1

        except Exception as e:
            print(e)
            pass

except Exception as e:                  
    print(e)
    pass

Processing pincode: 110001
Pincode Entry Success
500 ASINS Remaining B07G1C4YF2 None Currently unavailable.
We don't know when or if this item will be back in stock. None None NO 4.2 829  none
499 ASINS Remaining B07G1G4VCB Cocoblu Retail Only 3 left in stock. 429 450 NO 4.2 829  7 September
498 ASINS Remaining B07G1C4XK7 Cocoblu Retail In stock 393 429 NO 4.2 829  4 September
497 ASINS Remaining B07G1H1PD5 Cocoblu Retail In stock 259 None NO 4.2 1,797  4 September
496 ASINS Remaining B07G1KRYX2 Cocoblu Retail In stock 249 None NO 4.2 1,797  4 September
495 ASINS Remaining B07G1H5JKX Cocoblu Retail In stock 249 None NO 4.2 1,797  4 September
494 ASINS Remaining B07Z9JXXQ2 webrand seller Only 2 left in stock. 390 398 NO 4.0 807  6 September
493 ASINS Remaining B07Z9HCSSV webrand seller Only 1 left in stock. 390 398 NO 4.0 807  6 September
492 ASINS Remaining B07Z9JCKLP webrand seller Only 5 left in stock. 408 None NO 4.0 807  7 September
491 ASINS Remaining B07Z9HWXB4 None Currently unavailable.
We don't know when or if this item will be back in stock. None None NO 4.0 807  none
490 ASINS Remaining B09YLRDHCZ Cocoblu Retail In stock 399 None NO 4.2 355  4 September
489 ASINS Remaining B09YM3PRJM Cocoblu Retail In stock 419 None NO 4.2 355  4 September
488 ASINS Remaining B08231VT8K None Currently unavailable.
We don't know when or if this item will be back in stock. None None NO 4.2 529  none
487 ASINS Remaining B08231HXP5 None Currently unavailable.
We don't know when or if this item will be back in stock. None None NO 4.2 529  none
486 ASINS Remaining B08231KGYH None Currently unavailable.
We don't know when or if this item will be back in stock. None None NO 4.2 529  none
485 ASINS Remaining B08232BC4Z None Currently unavailable.
We don't know when or if this item will be back in stock. None None NO 4.2 529  none
484 ASINS Remaining B082327G9B webrand seller In stock 395 429 NO 4.0 807  6 September
483 ASINS Remaining B0823279PZ None Currently unavailable.
We don't know when or if this item will be back in stock. None None NO 4.0 807  none
482 ASINS Remaining B09SGF64NC None Currently unavailable.
We don't know when or if this item will be back in stock. None None NO 4.3 379  none
481 ASINS Remaining B09SGCM61Y None Currently unavailable.
We don't know when or if this item will be back in stock. None None NO 4.3 379  none
480 ASINS Remaining B09SGBKB7P Cocoblu Retail Only 1 left in stock. 588 None NO 4.3 379  6 September
479 ASINS Remaining B09SG9ZYZQ None Currently unavailable.
We don't know when or if this item will be back in stock. None None NO 4.3 379  none
478 ASINS Remaining B07B9PVXBT KUKU KI DUKAN Only 1 left in stock. 399 None NO 4.2 829  6 September
477 ASINS Remaining B07B9QHXFW None Currently unavailable.
We don't know when or if this item will be back in stock. None None NO 4.2 829  none
476 ASINS Remaining B0BKSKMR9T Cocoblu Retail In stock 450 None NO 4.4 333  4 September
475 ASINS Remaining B0BKRY4DJJ Cocoblu Retail In stock 450 None NO 4.4 333  4 September
474 ASINS Remaining B09SH8Y32K Cocoblu Retail In stock 498 None NO 4.4 697  4 September
473 ASINS Remaining B09SHC6N61 Cocoblu Retail In stock 498 None NO 4.4 697  4 September
472 ASINS Remaining B09YM21MDV Cocoblu Retail In stock 499 None NO 4.4 697  4 September
471 ASINS Remaining B09YM2D55R Cocoblu Retail In stock 498 None NO 4.4 697  4 September
470 ASINS Remaining B09SH971CY Cocoblu Retail In stock 478 None NO 4.4 697  4 September
469 ASINS Remaining B09SHC9LSF Cocoblu Retail In stock 478 None NO 4.4 697  4 September
468 ASINS Remaining B09SH9R6JL Cocoblu Retail In stock 478 None NO 4.4 697  4 September
467 ASINS Remaining B09SHLYY5M Cocoblu Retail In stock 479 498 NO 4.4 697  4 September
466 ASINS Remaining B085CWFVWR JockeyIndia In stock 299 None NO 4.4 1,189  6 September
465 ASINS Remaining B07R9Z72L6 Cocoblu Retail Only 5 left in stock. 259 None NO 4.3 105  6 September
464 ASINS Remaining B0BVZLGSKB Cocoblu Retail In stock 429 None NO 4.5 885  4 September
463 ASINS Remaining B07KQDG2M9 Add to Kart (Online Shop) In stock 149 169 NO 4.1 262  6 September
462 ASINS Remaining B09KV14V8X JockeyIndia In stock 149 None NO 4.0 328  8 September
461 ASINS Remaining B086THKNT4 Cocoblu Retail Available to ship in 1-2 days 149 None NO 4.1 5,461  5 September
460 ASINS Remaining B085FLJ1HR Cocoblu Retail In stock 169 None NO 4.2 4,131  4 September
459 ASINS Remaining B085D12BM5 JockeyIndia In stock 159 None NO 4.1 4,287  8 September
458 ASINS Remaining B01C886DXE JockeyIndia In stock 159 None NO 4.1 4,287  6 September
457 ASINS Remaining B01C886DSY Cocoblu Retail In stock 169 None NO 4.2 4,131  4 September
456 ASINS Remaining B00W0X7HN8 Cocoblu Retail In stock 169 None NO 4.2 4,131  6 September
455 ASINS Remaining B00W06GS1M Cocoblu Retail In stock 169 None NO 4.2 4,131  6 September
454 ASINS Remaining B00W06HWT4 JockeyIndia In stock 199 None NO 4.2 1,027  6 September
453 ASINS Remaining B085CZZ6NW JockeyIndia In stock 159 None NO 4.0 313  6 September
452 ASINS Remaining B00W06IDHO Add to Kart (Online Shop) In stock 129 159 NO 4.1 4,287  6 September
451 ASINS Remaining B00W06I1VW JockeyIndia In stock 159 None NO 4.1 4,287  6 September
450 ASINS Remaining B00W06GGZU JockeyIndia In stock 169 None NO 4.3 751  6 September
449 ASINS Remaining B0B5GM421D Cocoblu Retail In stock 298 None NO 4.4 733  4 September
448 ASINS Remaining B0B5GKKG2F JockeyIndia In stock 169 None NO 4.1 986  6 September
447 ASINS Remaining B0B4VWDV5Z Add to Kart (Online Shop) In stock 135 159 NO 4.2 239  6 September
446 ASINS Remaining B09RQHYG2H JockeyIndia In stock 99 None NO 4.1 2,087  6 September
445 ASINS Remaining B0B4ZQBB52 Cocoblu Retail In stock 462 None NO 4.3 1,453  4 September
444 ASINS Remaining B0B519N4TV JockeyIndia In stock 189 None NO 4.2 106  8 September
443 ASINS Remaining B0B5GPNJ5J Add to Kart (Online Shop) In stock 149 159 NO 3.9 529  6 September
442 ASINS Remaining B0B4VZCTL2 JockeyIndia In stock 169 None NO 4.1 986  8 September
441 ASINS Remaining B0B4VZTV9L Add to Kart (Online Shop) In stock 149 159 NO 4.2 239  6 September
440 ASINS Remaining B0B4W1GTXL JockeyIndia In stock 199 None NO 4.2 1,027  8 September
439 ASINS Remaining B0B4VTMD4V Add to Kart (Online Shop) In stock 133 169 NO 4.1 986  6 September
438 ASINS Remaining B0B517DGXY JockeyIndia In stock 149 None NO 4.1 5,461  6 September
437 ASINS Remaining B0BKZBTMXV JockeyIndia In stock 149 None NO 4.1 5,461  6 September
436 ASINS Remaining B0B4VX18WG Add to Kart (Online Shop) Only 1 left in stock. 135 169 NO 4.2 239  6 September
435 ASINS Remaining B0B5GJHS1F Add to Kart (Online Shop) In stock 139 159 NO 3.9 529  6 September
434 ASINS Remaining B0B519HCYH Cocoblu Retail In stock 274 279 NO 4.3 755  4 September
433 ASINS Remaining B0B4VXNSZS Add to Kart (Online Shop) In stock 133 169 NO 4.1 986  6 September
432 ASINS Remaining B0B5GK37GX Add to Kart (Online Shop) In stock 139 159 NO 3.9 529  6 September
431 ASINS Remaining B0B5GL5X7Q Add to Kart (Online Shop) In stock 139 159 NO 3.9 529  6 September
430 ASINS Remaining B01MQH36FL Add to Kart (Online Shop) In stock 923 1,050 NO 4.3 3,120  6 September
429 ASINS Remaining B015SGW0EY None  None None NO 4.0 2,350  none
428 ASINS Remaining B09MFNDBLM JockeyIndia In stock 539 None NO 4.2 725  8 September
427 ASINS Remaining B09MFL9W1N Cocoblu Retail Only 5 left in stock. 679 None NO 4.3 212  5 September
426 ASINS Remaining B09KV1ZBLJ Cocoblu Retail In stock 538 None NO 4.2 725  4 September
425 ASINS Remaining B09J17B3L8 Cocoblu Retail In stock 499 None NO 4.2 1,088  4 September
424 ASINS Remaining B078ZYFJ87 Cocoblu Retail In stock 299 None NO 4.1 8,358  4 September
423 ASINS Remaining B085BMLGFT Cocoblu Retail In stock 493 499 NO 4.3 108  4 September
422 ASINS Remaining B09KTYRSPP Cocoblu Retail In stock 349 None NO 4.2 2,828  4 September
421 ASINS Remaining B01ENC1UKY Cocoblu Retail In stock 279 None NO 4.0 8,148  4 September
420 ASINS Remaining B01ENCAA2I Cocoblu Retail In stock 349 None NO 4.2 2,828  4 September
419 ASINS Remaining B09KTZTTLR Cocoblu Retail In stock 539 None NO 4.2 725  4 September
418 ASINS Remaining B09KV2VSBR Cocoblu Retail In stock 539 None NO 4.2 725  4 September
417 ASINS Remaining B09KTZXFP4 Cocoblu Retail In stock 279 None NO 4.0 8,148  4 September
416 ASINS Remaining B086T92T8G None Currently unavailable.
We don't know when or if this item will be back in stock. None None NO 4.3 627  none
415 ASINS Remaining B07XJBJM7G Cocoblu Retail In stock 449 None NO 4.1 1,987  4 September
414 ASINS Remaining B07TJVMCG3 JockeyIndia In stock 449 None NO 4.1 1,987  6 September
413 ASINS Remaining B07KPW1MCF Cocoblu Retail In stock 699 None NO 4.2 3,229  4 September
412 ASINS Remaining B00W04N47U Cocoblu Retail In stock 449 None NO 4.1 1,987  4 September
411 ASINS Remaining B086T99RHK Cocoblu Retail In stock 599 None NO 4.4 12,691  4 September
410 ASINS Remaining B08JQFQ4WB Cocoblu Retail In stock 704 729 NO 4.2 3,229  4 September
409 ASINS Remaining B086T8N1XH Cocoblu Retail In stock 629 None NO 4.4 12,691  4 September
408 ASINS Remaining B01H5FXAAE Cocoblu Retail In stock 449 None NO 4.1 1,987  4 September
407 ASINS Remaining B09J15SL94 None Currently unavailable.
We don't know when or if this item will be back in stock. None None NO 4.2 1,088  none
406 ASINS Remaining B012SX6IIE Cocoblu Retail In stock 629 None NO 4.4 12,691  4 September
405 ASINS Remaining B07XMMZDN2 Cocoblu Retail In stock 599 None NO 4.4 12,691  4 September
404 ASINS Remaining B01CP5W1ZY Cocoblu Retail In stock 499 None NO 4.2 1,088  4 September
403 ASINS Remaining B089QYYNHP JockeyIndia In stock 699 None NO 4.2 3,229  6 September
402 ASINS Remaining B07KPLFLH4 Cocoblu Retail In stock 699 None NO 4.2 3,229  4 September
401 ASINS Remaining B01ENCAABO Cocoblu Retail In stock 349 None NO 4.2 2,828  4 September
Processing pincode: 400001
Message: element not interactable
  (Session info: chrome=139.0.7258.155)
Stacktrace:
	GetHandleVerifier [0x0x7ff7638a3d85+79397]
	GetHandleVerifier [0x0x7ff7638a3de0+79488]
	(No symbol) [0x0x7ff76364bf2c]
	(No symbol) [0x0x7ff7636984a7]
	(No symbol) [0x0x7ff7636cb19a]
	(No symbol) [0x0x7ff763695996]
	(No symbol) [0x0x7ff7636cb3b0]
	(No symbol) [0x0x7ff7636f3344]
	(No symbol) [0x0x7ff7636caf73]
	(No symbol) [0x0x7ff7636941b1]
	(No symbol) [0x0x7ff763694f43]
	GetHandleVerifier [0x0x7ff763b6e1ed+3005069]
	GetHandleVerifier [0x0x7ff763b6831d+2980797]
	GetHandleVerifier [0x0x7ff763b87e0d+3110573]
	GetHandleVerifier [0x0x7ff7638bd6de+184190]
	GetHandleVerifier [0x0x7ff7638c516f+215567]
	GetHandleVerifier [0x0x7ff7638ac974+115220]
	GetHandleVerifier [0x0x7ff7638acb29+115657]
	GetHandleVerifier [0x0x7ff763893268+11016]
	BaseThreadInitThunk [0x0x7ffd1cc0e8d7+23]
	RtlUserThreadStart [0x0x7ffd1dcc8d9c+44]

Processing pincode: 560001
Message: element not interactable
  (Session info: chrome=139.0.7258.155)
Stacktrace:
	GetHandleVerifier [0x0x7ff7638a3d85+79397]
	GetHandleVerifier [0x0x7ff7638a3de0+79488]
	(No symbol) [0x0x7ff76364bf2c]
	(No symbol) [0x0x7ff7636984a7]
	(No symbol) [0x0x7ff7636cb19a]
	(No symbol) [0x0x7ff763695996]
	(No symbol) [0x0x7ff7636cb3b0]
	(No symbol) [0x0x7ff7636f3344]
	(No symbol) [0x0x7ff7636caf73]
	(No symbol) [0x0x7ff7636941b1]
	(No symbol) [0x0x7ff763694f43]
	GetHandleVerifier [0x0x7ff763b6e1ed+3005069]
	GetHandleVerifier [0x0x7ff763b6831d+2980797]
	GetHandleVerifier [0x0x7ff763b87e0d+3110573]
	GetHandleVerifier [0x0x7ff7638bd6de+184190]
	GetHandleVerifier [0x0x7ff7638c516f+215567]
	GetHandleVerifier [0x0x7ff7638ac974+115220]
	GetHandleVerifier [0x0x7ff7638acb29+115657]
	GetHandleVerifier [0x0x7ff763893268+11016]
	BaseThreadInitThunk [0x0x7ffd1cc0e8d7+23]
	RtlUserThreadStart [0x0x7ffd1dcc8d9c+44]

Processing pincode: 500001
Message: no such element: Unable to locate element: {"method":"css selector","selector":"#GLUXZipUpdateInput"}
  (Session info: chrome=139.0.7258.155); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x0x7ff7638a3d85+79397]
	GetHandleVerifier [0x0x7ff7638a3de0+79488]
	(No symbol) [0x0x7ff76364c0fa]
	(No symbol) [0x0x7ff7636a2fd6]
	(No symbol) [0x0x7ff7636a328c]
	(No symbol) [0x0x7ff7636f6537]
	(No symbol) [0x0x7ff7636cb1df]
	(No symbol) [0x0x7ff7636f3344]
	(No symbol) [0x0x7ff7636caf73]
	(No symbol) [0x0x7ff7636941b1]
	(No symbol) [0x0x7ff763694f43]
	GetHandleVerifier [0x0x7ff763b6e1ed+3005069]
	GetHandleVerifier [0x0x7ff763b6831d+2980797]
	GetHandleVerifier [0x0x7ff763b87e0d+3110573]
	GetHandleVerifier [0x0x7ff7638bd6de+184190]
	GetHandleVerifier [0x0x7ff7638c516f+215567]
	GetHandleVerifier [0x0x7ff7638ac974+115220]
	GetHandleVerifier [0x0x7ff7638acb29+115657]
	GetHandleVerifier [0x0x7ff763893268+11016]
	BaseThreadInitThunk [0x0x7ffd1cc0e8d7+23]
	RtlUserThreadStart [0x0x7ffd1dcc8d9c+44]

Processing pincode: 700001
Message: element not interactable
  (Session info: chrome=139.0.7258.155)
Stacktrace:
	GetHandleVerifier [0x0x7ff7638a3d85+79397]
	GetHandleVerifier [0x0x7ff7638a3de0+79488]
	(No symbol) [0x0x7ff76364bf2c]
	(No symbol) [0x0x7ff7636984a7]
	(No symbol) [0x0x7ff7636cb19a]
	(No symbol) [0x0x7ff763695996]
	(No symbol) [0x0x7ff7636cb3b0]
	(No symbol) [0x0x7ff7636f3344]
	(No symbol) [0x0x7ff7636caf73]
	(No symbol) [0x0x7ff7636941b1]
	(No symbol) [0x0x7ff763694f43]
	GetHandleVerifier [0x0x7ff763b6e1ed+3005069]
	GetHandleVerifier [0x0x7ff763b6831d+2980797]
	GetHandleVerifier [0x0x7ff763b87e0d+3110573]
	GetHandleVerifier [0x0x7ff7638bd6de+184190]
	GetHandleVerifier [0x0x7ff7638c516f+215567]
	GetHandleVerifier [0x0x7ff7638ac974+115220]
	GetHandleVerifier [0x0x7ff7638acb29+115657]
	GetHandleVerifier [0x0x7ff763893268+11016]
	BaseThreadInitThunk [0x0x7ffd1cc0e8d7+23]
	RtlUserThreadStart [0x0x7ffd1dcc8d9c+44]

CPU times: total: 2.97 s
Wall time: 8min 53s

In [13]:
data_1 =pd.DataFrame(list(zip(asin,title,stock,seller,pin_df,buybox,price,mrp,free_delivery,fast_delivery,bsr,fresh_avail,fresh_price,fresh_seller,star_rating,no_of_rating,current_hours)),columns=['ASIN','Title','Availability','Seller','Pin','Buy Now','Price','MRP','Free_Delivery','Fast_Delivery','BSR','Fresh_Available','fresh_price','Fresh_seller','ratings','Total Ratings','hour'])
data_1.tail(2)

,ASIN,Title,Availability,Seller,Pin,Buy Now,Price,MRP,Free_Delivery,Fast_Delivery,BSR,Fresh_Available,fresh_price,Fresh_seller,ratings,Total Ratings,hour
98,B07KPLFLH4,Jockey IC30 Men's Tactel Microfiber Elastane S...,In stock,Cocoblu Retail,110001,Yes,699,None,4 September,3 September,#623 in Clothing & Accessories (See Top 100 i...,NO,none,None,4.2,"3,229",13
99,B01ENCAABO,Jockey US60 Men's Super Combed Cotton Elastane...,In stock,Cocoblu Retail,110001,Yes,349,None,4 September,3 September,"#3,443 in Clothing & Accessories (See Top 100...",NO,none,None,4.2,"2,828",13

In [ ]:
data_1['Free_Delivery'] = pd.to_datetime(data_1['Free_Delivery'], errors='coerce', format='%d %b', exact=False) \
                  .combine_first(pd.to_datetime(data_1['Free_Delivery'], errors='coerce', format='%B %d', exact=False))

data_1['Fast_Delivery'] = pd.to_datetime(data_1['Fast_Delivery'], errors='coerce', format='%d %b', exact=False) \
                  .combine_first(pd.to_datetime(data_1['Fast_Delivery'], errors='coerce', format='%B %d', exact=False))


current_year = datetime.datetime.now().year
data_1['Free_Delivery'] = data_1['Free_Delivery'].apply(lambda x: x.replace(year=current_year))
data_1['Fast_Delivery'] = data_1['Fast_Delivery'].apply(lambda x: x.replace(year=current_year))

data_1['Free_Delivery'] = data_1['Free_Delivery'].dt.date
data_1['Fast_Delivery'] = data_1['Fast_Delivery'].dt.date

data_1['Date'] = datetime.date.today()
data_1.head(2)

In [ ]:
final_df=data_1

In [ ]:
final_df['Delivery_Days'] = final_df['Free_Delivery'] - final_df['Date']

final_df['Delivery_Days'] = final_df['Delivery_Days'].astype(str).str.replace(' days','').str.replace(' day','')

data_bsr = final_df['BSR'].str.replace('in','').str.split('#',expand=True)

try:
    final_df['noding_rank_1'] = data_bsr[1].str.split('(',expand=True)[0].str.split(' ',n=1,expand=True)[0]
    final_df['noding_category_1'] = data_bsr[1].str.split('(',expand=True)[0].str.split(' ',n=1,expand=True)[1]
except:
    final_df['noding_rank_1'] = 'None'
    final_df['noding_category_1'] = 'None'
    

try:
    final_df['noding_rank_2'] = data_bsr[2].str.split('(',expand=True)[0].str.split(' ',n=1,expand=True)[0]
    final_df['noding_category_2'] = data_bsr[2].str.split('(',expand=True)[0].str.split(' ',n=1,expand=True)[1]
except:
    final_df['noding_rank_2'] = 'None'
    final_df['noding_category_2'] = 'None'

    
try:
    final_df['noding_rank_3'] = data_bsr[3].str.split('(',expand=True)[0].str.split(' ',n=1,expand=True)[0]
    final_df['noding_category_3'] = data_bsr[3].str.split('(',expand=True)[0].str.split(' ',n=1,expand=True)[1]
except:
    final_df['noding_rank_3'] = 'None'
    final_df['noding_category_3'] = 'None'
    
    
try:
    final_df['noding_rank_4'] = data_bsr[4].str.split('(',expand=True)[0].str.split(' ',n=1,expand=True)[0]
    final_df['noding_category_4'] = data_bsr[4].str.split('(',expand=True)[0].str.split(' ',n=1,expand=True)[1]
except:
    final_df['noding_rank_4'] = 'None'
    final_df['noding_category_4'] = 'None'

In [ ]:
final_df.columns

In [ ]:
final_df.columns = [col.replace(' ','_').lower() for col in final_df.columns]
final_df.shape

In [ ]:
final_df['availability'] = np.where(final_df['buy_now'] == 'Yes', 'In Stock', 'Out Of Stock')

In [ ]:
df_final=pd.merge(final_df,asins_sheet,on='asin',how='left')

In [ ]:
df_final['hour']

In [ ]:
df_final['delivery_days'] = df_final['delivery_days'].astype(str).str.split(',').str[0]

In [ ]:
df_final['bsr']=df_final['bsr'].astype(str)

In [ ]:
df_final

In [ ]:
df_final.columns

In [ ]:
from sqlalchemy import create_engine
engine = create_engine('postgresql+psycopg2://postgres:tr0ub4dor&3@nucleus.ckojnefw0d56.us-west-1.rds.amazonaws.com/GIF_2025')

df_final.to_sql('amazon_buybox', engine, if_exists='append', index=False)

In [ ]:
browser.quit()

In [ ]:
# df_final