# Flipkart_Buybox

In [1]:
from bs4 import BeautifulSoup
from datetime import timedelta
from datetime import datetime
from requests.auth import HTTPBasicAuth
import requests
import time
import re
import pandas as pd
from datetime import datetime
from datetime import date
from gspread_pandas import Spread,Client
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.firefox.firefox_binary import FirefoxBinary
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support.ui import Select
global driver
import warnings
warnings.filterwarnings("ignore")

my_credentials={
  "type": "service_account",
  "project_id": "crafty-plateau-328717",
  "private_key_id": "4afdb5a0906054d2d69cd46b2e8af41b73b9b8a7",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDcQv0qyESqHiYz\n82V5rSDiEG8xMGF0hIC9cJirwrDgAhEpjKIQRnJ227g6CP/8CTYYSrvJXmGzTZrB\n+FtrYWeZPjuIZGPyPJShIG//4LWcjlnh/h5zilKcmyaKsu5M0BSWiW0rkIUwYFgS\nox6xfiW3UbYWIUAGVvwDBYopUExaEV/a9l8p43pKDXHmZfq4ZIu2XgLDqalDLbCW\n1FjU7umMWS9KEvibo6mUkia9kkw1DvEsIkbWny3Bm0SoDLeqG0B6OsXhOYMfEJ+W\nSR80TR4Fu+EVfzRocwNVQHOKB2o0mbd/0AA1z/OPGM99QJXXKm8+CdV0KTbj6MUB\ns2/YTlG5AgMBAAECggEAKJ8IHrhBhZg61nDogYiu3FJIl2tDReBb99QIrACjaySm\ncqG3j8XWPVpnPvjC8QHn4pIB0PDhltZUmLpLbeHQX+AszYoqLpYCmTaowSl5hO5x\n4C5kAk37z1sDwCegsDTd3ydoJVUpYxMZmxJPSk+n+AePS8SFEMZBAvOmF9lxw1hC\nJoYkw4/H9XvuW7fTiOK2le6GokWgDUqSgTQRHO78NION1Z5pB5ymAKrV7w5GH4LI\nkFIuOxQEHhLv0a2URVEzkHX3VGPbBHF4MQ/Z8ObxqEsefkOnEpRIRTsE8+G44coB\nYbVdhe0132qgotEN1GvsBLwq+TJIknt38jkDcs9sKwKBgQD+sGqDtvCzSz5rk/Xg\nNHFOq9FsWSeUuw9jxw4XJxVqYbJbLcy0DmfIPg1rZgPW8X+6upt5RigHVBixqz74\nsnP9IvmVuoU6s9VoW1HaYbnbg5Zqp3WFa6xHZv/vXIapfCX8binEsVWwYW2gb2AJ\nE13jFJWZB7n8zatEk9ho1Rv50wKBgQDdZTXjsc0N3DZhCR39zPGr811VBmnXuUwW\nG1MG7z4npe2eFeTYHepKN8c3Ot+boyDm+K+NsEYHLH6wlcXFxMHAgSY6xAe8k+4i\n8EgwgUPfmawUrv7tXsAhASZNJwoE4S9S/kY/WFJR6CddaMUYvNtle5P99D//uoGG\nXcJWdEsiwwKBgQDBNaoIM98T1RAMYlmTdZVDfjrIPDY3sVSyd85rp/2qD2VToEH7\nkjYPBWv+voxJIjmouWm6rYsuTBDTr7p8xjwRm9fFS5NIfiZ2HVjSF3L8YS3ZySHx\nTkaKgEvGFOYfawwSHKxZB8KepLqajANJv0RpQTNfvSnN62RzCMmSdaDcewKBgQC8\nKuprdNHYRuL9BDe2X7rDr5sSydmpnPa7D0w455wHLLLRmsAeowZfQBsUqPgmGra7\nOIBUx44tSLcAtLscBMe8KshoR/ZfY8eRcHGasDMU11J3XeiTrOVU59o61sRgM1f6\njNz9t753mP3kGUjzZoh+L1MwE6lVW5n8rrGes0as6wKBgE54ZYZcUXRbOh+d1I9e\njWfwqr/mfvVGUZIBP4qDgL4dNHPWzWT7gjZIQUWJyXIMjP+04dly5ugJIX5UEC1M\nWPH1f9nsW3tvSp5suycEvtyXqEqrudLTHPOKhFWFDdh1bpO6y6GuAXMBU7FywTgi\n49Cl8Nil36anL8yJHhf7RSOF\n-----END PRIVATE KEY-----\n",
  "client_email": "aakashgooglesheets@crafty-plateau-328717.iam.gserviceaccount.com",
  "client_id": "108448941747378112883",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/aakashgooglesheets%40crafty-plateau-328717.iam.gserviceaccount.com"
}

In [2]:
spread = Spread('GIF_2025_Mapping_Requirement',config=my_credentials) ## worksheet_name
sheet=spread.open_sheet("Flipkart_BuyBox") ##sheet_name
data=spread.sheet_to_df(sheet=sheet,index=0)
data.head()

,fsn,account,category,sub_category,sub_category_1,sub_category_2,sub_category_3
0,BRFEGFW8XZJTKVYG,Jockey,MIW,brief,Brief,,
1,BRFEGFW8EHRF4X2E,Jockey,MIW,brief,Brief,,
2,BRFEGFW8Y2YJ3HRD,Jockey,MIW,brief,Brief,,
3,BRFEGFW8Y7JSZUN7,Jockey,MIW,brief,Brief,,
4,BRFFQZJXENHCPTBE,Jockey,MIW,brief,Brief,,

In [3]:
cols = []
for col in data.columns:
    cols.append(col.lower())

data.columns = cols
df_=data

In [4]:
fk_sku = data['fsn'].to_list()
len(fk_sku)

4700

In [5]:
# flipkart_buybox_prime_25
# fk_sku=fk_sku[:75]               # Rohit
# fk_sku=fk_sku[75:150]            # Ajay
# fk_sku=fk_sku[150:225]           # Koushik
# fk_sku=fk_sku[225:300]          # Surya
# fk_sku=fk_sku[300:375]          # shruthi
# fk_sku=fk_sku[375:450]          # jibin
# fk_sku=fk_sku[450:525]          # karnakaran
# fk_sku=fk_sku[525:600]           # Hemanth
# fk_sku=fk_sku[600:675]           # sumit
# fk_sku=fk_sku[675:750]           # Harish
# fk_sku=fk_sku[750:835]           # Hari Prasad
# fk_sku=fk_sku[825:900]           # Rishab
fk_sku=fk_sku[4600:4700]                # Rajshekhar

In [6]:
len(fk_sku)

100

In [7]:
fk_pincode = ['560001','400001','110001','500001','700001'
              ]
len(fk_pincode)

5

In [8]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
import time
import os
# Path to ChromeDriver
# chrome_driver_path = r"C:\Users\Rajashekar\Downloads\chromedriver-win64 (5)\chromedriver-win64\chromedriver.exe" # <-- change this to your actual path
# # Set download directory
# download_dir = r"C:\Your\Download\Path"  # <-- change this to your desired download path
# Set Chrome options
options = Options()
prefs = {
    # "download.default_directory": download_dir,
    "download.prompt_for_download": False,
    "download.directory_upgrade": True,
    "plugins.always_open_pdf_externally": True,
    "profile.default_content_settings.popups": 0,
    "profile.content_settings.exceptions.automatic_downloads.*.setting": 1
}
options.add_experimental_option("prefs", prefs)
options.add_argument("--start-maximized")  # Optional
# Initialize driver
# service = Service(executable_path=chrome_driver_path)
# driver = webdriver.Chrome(service=service, options=options)
driver = webdriver.Chrome()
# Use the driver
time.sleep(5)
driver.get('https://www.flipkart.com/')
wait = WebDriverWait(driver, 5)

In [ ]:
%%time
import pytz
tz = pytz.timezone('Asia/Kolkata')
fk_stock=[]
fk_sold_by=[]
fk_sku1=[]
fk_name=[]
fk_ratings1 = []
fk_noofratings1 = []
fk_full_prices1=[]
fk_noofreviews=[]
fk_mrp1 = []
fk_free_del = []
fk_pincode_input=[]
fk_hour=[]
count=len(fk_sku)*len(fk_pincode)
html = driver.page_source
soup = BeautifulSoup(html, "html.parser")

for j in fk_pincode:
    print("pincodes ", j)
    time.sleep(3)
    url = f"https://www.flipkart.com/protinex-original/p/itm36d85b298a471?pid=MDMGEXMXSJV6FAQ4"
    driver.get(url)     
    driver.refresh()
    time.sleep(0.8)
    keys = driver.find_element(By.CSS_SELECTOR, '#pincodeInputId')
    keys.click()
    time.sleep(1)
    keys.clear()
    time.sleep(1)
    keys.send_keys(j)
    time.sleep(1)
    try:
        driver.find_element(By.CSS_SELECTOR, '._2P_LDn').click()
        time.sleep(2)
    except:
        try:
            driver.find_element(By.XPATH,'/html/body/div[1]/div/div[3]/div[1]/div[2]/div[4]/div/div/div[1]/div[2]/div/div[2]/div[1]/span').click()
            time.sleep(2)
        except:
            pass
    for i in fk_sku:
        url = f"https://www.flipkart.com/onlyleaf-hibiscus-cinnamon-clove-green-tea-27-pyramid-bags-made-100-whole-leaf-natural-hibiscus-25-bags-2-free-samples-box/p/itm94c0b457d3b0d?pid={i}"
        driver.get(url)
        WebDriverWait(driver, 10).until(
            EC.presence_of_element_located((By.TAG_NAME, 'body')))
        time.sleep(0.8)
        
        fk_pincode_input.append(j)
        try:
            fk_name.append(driver.find_element(By.CSS_SELECTOR,'.VU-ZEz').text)
        except:
            fk_name.append("None")
        try:
            fk_sku1.append(i)
        except:
            fk_sku1.append('None')
        try:
            fk_sold_by.append(driver.find_element(By.CSS_SELECTOR,'#sellerName > span:nth-child(1) > span:nth-child(1)').text)
        except:
            fk_sold_by.append('None')
    
        try:
            fk_full_prices1.append(re.findall(r'\d+',driver.find_element(By.CSS_SELECTOR,'.CxhGGd').text.replace(",",""))[0])
        except:
            try:
                fk_full_prices1.append(re.findall(r'\d+',driver.find_element(By.CSS_SELECTOR,'._16Jk6d').text.replace(",",""))[0])
            except:
                fk_full_prices1.append(0)
        
        try:
            fk_mrp1.append(re.findall(r'\d+',driver.find_element(By.CSS_SELECTOR,'.A6\+E6v').text.replace(",",""))[0])
        except:
            try:
                fk_mrp1.append(re.findall(r'\d+',driver.find_element(By.CSS_SELECTOR,'._16Jk6d').text.replace(",",""))[0])
            except:
                fk_mrp1.append(0)
                
        try:
            if(driver.find_element(By.CSS_SELECTOR,"._1NQ_ER").text=='Currently out of stock in this area.'):
                fk_stock.append('Out of stock')
                
        except:
            try:
                if(driver.find_element(By.CSS_SELECTOR,".In9uk2")):
                    fk_stock.append('Instock')
            except:
                fk_stock.append('Out of stock')
        try:
            fk_free_del.append(driver.find_element(By.CSS_SELECTOR,'._1TPvTK').text)
        except:
            fk_free_del.append("None")  
        try:
            fk_ratings1.append(driver.find_element(By.CSS_SELECTOR,'#productRating_LSTBKPH3GQ8QF6MSJCMHPECKZ_BKPH3GQ8QF6MSJCM_ > div').text)
        except:
            try:
                fk_ratings1.append(driver.find_element(By.CSS_SELECTOR,'#productRating_LSTPRCEZZRJ8ZGVC3HA2FNX4W_PRCEZZRJ8ZGVC3HA_').text)
            except:
                try:
                  fk_ratings1.append(driver.find_element(By.CSS_SELECTOR,'#productRating_LSTTRKFGYFWQBQMTSKQDMB6OD_TRKFGYFWQBQMTSKQ_ > div').text)  
                except:
                    try:
                        fk_ratings1.append(driver.find_element(By.CSS_SELECTOR,'#productRating_null_BRAG6WTX8FX3CTHF_ > div').text) 
                    except:
                        try:
                            fk_ratings1.append(driver.find_element(By.CSS_SELECTOR,'#productRating_LSTBRAG6WTXTDB5NQPA67LSWK_BRAG6WTXTDB5NQPA_ > div').text) 
                        except:
                            try:
                                fk_ratings1.append(driver.find_element(By.CSS_SELECTOR,'#productRating_LSTBRAG6WTX8GH93QJZ47PRB1_BRAG6WTX8GH93QJZ_ > div').text)
                            except:
                                try:
                                    fk_ratings1.append(driver.find_element(By.CSS_SELECTOR,'#productRating_LSTBRAG6WTXKFFGVNHVE9RATC_BRAG6WTXKFFGVNHV_ > div').text)
                                except:
                                    try:
                                        element = soup.find("div", class_="XQDdHH _1Quie7")
                                        # print(element)
                                        fk_ratings1.append(element.text.strip())
                                    except:
                                        fk_ratings1.append(0)

        try:
            fk_noofratings1.append(driver.find_element(By.CSS_SELECTOR,'#container > div > div._39kFie.N3De93.JxFEK3._48O0EI > div.DOjaWF.YJG4Cf > div.DOjaWF.gdgoEp.col-8-12 > div:nth-child(2) > div > div.DRxq-P > div > div > span.Wphh3N > span').text)
        except:
            try:
                fk_noofratings1.append(driver.find_element(By.CSS_SELECTOR,'#container > div > div._39kFie.N3De93.JxFEK3._48O0EI > div.DOjaWF.YJG4Cf > div.DOjaWF.gdgoEp.col-8-12 > div.DOjaWF.gdgoEp > div > div > div:nth-child(2) > div > div.OVvZks > div._5OesEi.R9XIbt.VWRXZO > span.Wphh3N.d4OmzS > span').text)
            except:
                fk_noofratings1.append(0)
        
        try:
            fk_noofreviews.append(driver.find_element(By.CSS_SELECTOR,'#container > div > div._39kFie.N3De93.JxFEK3._48O0EI > div.DOjaWF.YJG4Cf > div.DOjaWF.gdgoEp.col-8-12 > div:nth-child(2) > div > div.DRxq-P > div > div > span.Wphh3N > span').text)
        except:
            try:
                fk_noofreviews.append(driver.find_element(By.CSS_SELECTOR,'#container > div > div._39kFie.N3De93.JxFEK3._48O0EI > div.DOjaWF.YJG4Cf > div.DOjaWF.gdgoEp.col-8-12 > div.DOjaWF.gdgoEp > div > div > div:nth-child(2) > div > div.OVvZks > div._5OesEi.R9XIbt.VWRXZO > span.Wphh3N.d4OmzS > span').text)
            except:
                fk_noofreviews.append(0)
        col_name = datetime.now(tz=tz).strftime("%H")
        fk_hour.append(col_name)
        time.sleep(1)
        print(count,i,j,fk_stock[-1],fk_full_prices1[-1],fk_mrp1[-1],fk_sold_by[-1])
        count-=1

pincodes  560001
500 BRAGACZKZRH7SPNP 560001 Out of stock 829 0 None
499 BRAGACZKSCZFGNTA 560001 Out of stock 0 0 None
498 BRAFG29ZDKMZRYYY 560001 Instock 799 0 JockeyIndia
497 BRAFG29ZBYFAXAVY 560001 Instock 829 0 JockeyIndia
496 BRAFG29ZSDSGHG6A 560001 Instock 799 0 JockeyIndia
495 BRAFG29ZYS62CYFU 560001 Instock 799 0 JockeyIndia
494 BRAFG29ZTGVHMF5Z 560001 Instock 799 0 JockeyIndia
493 BRAFG29ZZGPXZWZU 560001 Instock 829 0 JockeyIndia
492 BRAFG29ZUHPHDX4Z 560001 Instock 799 0 JockeyIndia
491 BRAFG29ZFASHMTZT 560001 Instock 799 0 JockeyIndia
490 BRAFG29ZUZSZDYAD 560001 Instock 799 0 JockeyIndia
489 BRAFG29ZUCSCWXZD 560001 Instock 829 0 JockeyIndia
488 BRAFG29ZSDPZPEM3 560001 Instock 829 0 JockeyIndia
487 BRAFG29ZGF562HBP 560001 Instock 829 0 JockeyIndia
486 BRAFG29ZFHNMHZVZ 560001 Instock 829 0 JockeyIndia
485 BRAGFXFCCGFGR8NH 560001 Instock 799 0 JockeyIndia
484 BRAGFXFCWCSPBQ5J 560001 Instock 829 0 JockeyIndia
483 BRAGFXFCHHFVBYAV 560001 Instock 799 0 JockeyIndia
482 BRAGFXFCK3VEBZ8H 560001 Instock 829 0 JockeyIndia
481 BRAGFXFC4NYHG9GB 560001 Instock 799 0 JockeyIndia
480 BRAGFXFCU73WMBGZ 560001 Instock 799 0 JockeyIndia
479 BRAGFXFCYU7ARRJV 560001 Instock 829 0 JockeyIndia
478 BRAGFXFCTYRGJBRB 560001 Instock 799 0 JockeyIndia
477 BRAGFXFCZ2CUPXRU 560001 Instock 799 0 JockeyIndia
476 BRAGFXFCHTFFAKBA 560001 Instock 799 0 JockeyIndia
475 BRAGFXFCQZWFG3UM 560001 Instock 829 0 JockeyIndia
474 BRAGFXFC6PR26APY 560001 Out of stock 829 0 Kukukidukaan4
473 BRAGFXFQKBZKB9HY 560001 Instock 829 0 JockeyIndia
472 BRAGFXFCW8GWWRFT 560001 Instock 829 0 JockeyIndia
471 BRAFG29ZDRR9M9UC 560001 Out of stock 899 0 RetailNet
470 BRAFG29Z6RSEXGBU 560001 Out of stock 929 0 RetailNet
469 BRAFG29Z2SMWYHUG 560001 Out of stock 899 0 RetailNet
468 BRAFG29ZBHYEEWNJ 560001 Instock 929 0 JockeyIndia
467 BRAFG29ZBHPHEETF 560001 Instock 899 0 JockeyIndia
466 BRAFG29Z2GTNRQWD 560001 Out of stock 899 0 RetailNet
465 BRAFG29ZFYUAYNRK 560001 Out of stock 649 0 RetailNet
464 BRAFG29ZH6RASYPZ 560001 Instock 899 0 JockeyIndia
463 BRAFG29ZMWED5HXG 560001 Out of stock 899 0 RetailNet
462 BRAFG29ZUHUJ7YET 560001 Out of stock 0 0 None
461 BRAFG29ZNKCTCVX8 560001 Out of stock 0 0 None
460 BRAFG29ZECGF22FZ 560001 Out of stock 0 0 None
459 BRAFG29ZQPR5KVSZ 560001 Out of stock 0 0 None
458 BRAFG29ZNYKSHH9Q 560001 Out of stock 0 0 None
457 BRAG6WTXWBHVDGSN 560001 Instock 949 0 JockeyIndia
456 BRAG6WTXQ66UMSXF 560001 Instock 979 0 JockeyIndia
455 BRAG6WTXNPHGEHNC 560001 Instock 949 0 JockeyIndia
454 BRAG6WTXFAHHNB5R 560001 Instock 979 0 JockeyIndia
453 BRAG6WTXB6NCMHHY 560001 Instock 949 0 JockeyIndia
452 BRAG6WTXYPQYBU94 560001 Instock 949 0 JockeyIndia
451 BRAG6WTXUYHXAZTJ 560001 Out of stock 979 0 Kukukidukaan4
450 BRAG6WTXHT4YRGMZ 560001 Instock 949 0 JockeyIndia
449 BRAG6WTXSKREGAZX 560001 Instock 949 0 JockeyIndia
448 BRAG6WTXQAESWZ96 560001 Instock 949 0 JockeyIndia
447 BRAG6WTXVG9N2PGT 560001 Instock 979 0 JockeyIndia
446 BRAG6WTXEJJYEC6V 560001 Instock 979 0 JockeyIndia
445 BRAG6WTXEY6TGPE3 560001 Instock 979 0 JockeyIndia
444 BRAG6WTXDYNSK5PA 560001 Instock 979 0 JockeyIndia
443 BRAGMT4CDFMCCVC5 560001 Instock 949 0 JockeyIndia
442 BRAGMT4CGGR3TMPD 560001 Instock 979 0 JockeyIndia
441 BRAGMT4CZGHSC2GN 560001 Instock 949 0 JockeyIndia
440 BRAGMT4CBZKNSKZF 560001 Instock 979 0 JockeyIndia
439 BRAGMT4CCHKHEU6C 560001 Instock 949 0 JockeyIndia
438 BRAGMT4CMQSHC47U 560001 Instock 949 0 JockeyIndia
437 BRAGMT4CKTHFMHWE 560001 Instock 979 0 JockeyIndia
436 BRAGMT4CGNMDUJ59 560001 Instock 949 0 JockeyIndia
435 BRAGMT4CSYYNCXT3 560001 Instock 949 0 JockeyIndia
434 BRAGMT4CZT3E8HSZ 560001 Instock 949 0 JockeyIndia
433 BRAGMT4CDHGKEJPF 560001 Instock 979 0 JockeyIndia
432 BRAGMT4CBFBE8UWE 560001 Instock 979 0 JockeyIndia
431 BRAGMT4CW9HX72NK 560001 Instock 979 0 JockeyIndia
430 BRAGMT4CTDXRPMKU 560001 Out of stock 979 0 Kukukidukaan4
429 BRAG6WTXGF5ESSGY 560001 Instock 949 0 JockeyIndia
428 BRAG6WTXJMYJ93Z3 560001 Instock 979 0 JockeyIndia
427 BRAG6WTXBHFB2GMY 560001 Instock 949 0 JockeyIndia
426 BRAG6WTX5CAPD2H7 560001 Instock 979 0 JockeyIndia
425 BRAG6WTXRSPGBXUZ 560001 Instock 949 0 JockeyIndia
424 BRAG6WTXKJEUPJBS 560001 Instock 949 0 JockeyIndia
423 BRAG6WTXJ3RZKVZT 560001 Instock 979 0 JockeyIndia
422 BRAG6WTXRJWJGPGE 560001 Instock 949 0 JockeyIndia
421 BRAG6WTXG8PKPTRH 560001 Instock 949 0 JockeyIndia
420 BRAG6WTX8GH93QJZ 560001 Instock 949 0 JockeyIndia
419 BRAG6WTXKFFGVNHV 560001 Instock 979 0 JockeyIndia
418 BRAG6WTXPJRBT2FS 560001 Instock 979 0 JockeyIndia
417 BRAG6WTXQD9SXEVY 560001 Instock 979 0 JockeyIndia
416 BRAG6WTX8FX3CTHF 560001 Out of stock 0 0 None
415 BRAG6WTXTU9UNHC8 560001 Instock 949 0 JockeyIndia
414 BRAG6WTXMZAW5GF6 560001 Instock 979 0 JockeyIndia
413 BRAG6WTXJNMGMGAZ 560001 Instock 949 0 JockeyIndia
412 BRAG6WTXVJZQQBSF 560001 Instock 979 0 JockeyIndia
411 BRAG6WTXBG4NWBSA 560001 Instock 949 0 JockeyIndia
410 BRAG6WTXYB4QQCPT 560001 Instock 949 0 JockeyIndia
409 BRAG6WTXYCHETDGF 560001 Instock 979 0 JockeyIndia
408 BRAG6WTXDKHK27AJ 560001 Instock 949 0 JockeyIndia
407 BRAG6WTXM8XMQZSE 560001 Instock 949 0 JockeyIndia
406 BRAG6WTXGMYDEBFX 560001 Instock 949 0 JockeyIndia
405 BRAG6WTXSGGBZSGZ 560001 Out of stock 979 0 JockeyIndia
404 BRAG6WTX9DXKDKCM 560001 Instock 979 0 JockeyIndia
403 BRAG6WTXZ5NEMYYM 560001 Instock 979 0 JockeyIndia
402 BRAG6WTXTDB5NQPA 560001 Out of stock 979 0 Kukukidukaan4
401 TRKFGYFWQBQMTSKQ 560001 Out of stock 509 0 Kukukidukaan4
pincodes  400001
400 BRAGACZKZRH7SPNP 400001 Out of stock 829 0 None
399 BRAGACZKSCZFGNTA 400001 Out of stock 0 0 None
398 BRAFG29ZDKMZRYYY 400001 Instock 799 0 JockeyIndia
397 BRAFG29ZBYFAXAVY 400001 Instock 829 0 JockeyIndia
396 BRAFG29ZSDSGHG6A 400001 Instock 799 0 JockeyIndia
395 BRAFG29ZYS62CYFU 400001 Instock 799 0 JockeyIndia
394 BRAFG29ZTGVHMF5Z 400001 Instock 799 0 JockeyIndia
393 BRAFG29ZZGPXZWZU 400001 Instock 829 0 JockeyIndia
392 BRAFG29ZUHPHDX4Z 400001 Instock 799 0 JockeyIndia
391 BRAFG29ZFASHMTZT 400001 Instock 799 0 JockeyIndia
390 BRAFG29ZUZSZDYAD 400001 Instock 799 0 JockeyIndia
389 BRAFG29ZUCSCWXZD 400001 Instock 829 0 JockeyIndia
388 BRAFG29ZSDPZPEM3 400001 Instock 829 0 JockeyIndia
387 BRAFG29ZGF562HBP 400001 Instock 829 0 JockeyIndia
386 BRAFG29ZFHNMHZVZ 400001 Instock 829 0 JockeyIndia
385 BRAGFXFCCGFGR8NH 400001 Instock 799 0 JockeyIndia
384 BRAGFXFCWCSPBQ5J 400001 Instock 829 0 JockeyIndia
383 BRAGFXFCHHFVBYAV 400001 Instock 799 0 JockeyIndia
382 BRAGFXFCK3VEBZ8H 400001 Instock 829 0 JockeyIndia
381 BRAGFXFC4NYHG9GB 400001 Instock 799 0 JockeyIndia
380 BRAGFXFCU73WMBGZ 400001 Instock 799 0 JockeyIndia
379 BRAGFXFCYU7ARRJV 400001 Instock 829 0 JockeyIndia
378 BRAGFXFCTYRGJBRB 400001 Instock 799 0 JockeyIndia
377 BRAGFXFCZ2CUPXRU 400001 Instock 799 0 JockeyIndia
376 BRAGFXFCHTFFAKBA 400001 Instock 799 0 JockeyIndia
375 BRAGFXFCQZWFG3UM 400001 Instock 829 0 JockeyIndia
374 BRAGFXFC6PR26APY 400001 Out of stock 829 0 Kukukidukaan4
373 BRAGFXFQKBZKB9HY 400001 Instock 829 0 JockeyIndia
372 BRAGFXFCW8GWWRFT 400001 Instock 829 0 JockeyIndia
371 BRAFG29ZDRR9M9UC 400001 Out of stock 899 0 RetailNet
370 BRAFG29Z6RSEXGBU 400001 Out of stock 929 0 RetailNet
369 BRAFG29Z2SMWYHUG 400001 Out of stock 899 0 RetailNet
368 BRAFG29ZBHYEEWNJ 400001 Instock 929 0 JockeyIndia
367 BRAFG29ZBHPHEETF 400001 Instock 899 0 JockeyIndia
366 BRAFG29Z2GTNRQWD 400001 Out of stock 899 0 RetailNet
365 BRAFG29ZFYUAYNRK 400001 Out of stock 649 0 RetailNet
364 BRAFG29ZH6RASYPZ 400001 Instock 899 0 JockeyIndia
363 BRAFG29ZMWED5HXG 400001 Out of stock 899 0 RetailNet
362 BRAFG29ZUHUJ7YET 400001 Out of stock 0 0 None
361 BRAFG29ZNKCTCVX8 400001 Out of stock 0 0 None
360 BRAFG29ZECGF22FZ 400001 Out of stock 0 0 None
359 BRAFG29ZQPR5KVSZ 400001 Out of stock 0 0 None
358 BRAFG29ZNYKSHH9Q 400001 Out of stock 0 0 None
357 BRAG6WTXWBHVDGSN 400001 Instock 949 0 JockeyIndia
356 BRAG6WTXQ66UMSXF 400001 Instock 979 0 JockeyIndia

In [ ]:
fk_df=pd.DataFrame(list(zip(fk_sku1,fk_name,fk_pincode_input,fk_stock,fk_sold_by,fk_ratings1,fk_noofratings1,fk_noofreviews,
                        fk_full_prices1,fk_mrp1,fk_free_del,fk_hour)),columns=['fsn','title','pincode','availability','seller','rating','no_of_ratings','no_of_reviews','selling_price','mrp','free_delivery','hour'])

In [ ]:
fk_df['date']=date.today().strftime("%Y-%m-%d") 
fk_df['platform']="Flipkart"
fk_df=fk_df[['date','fsn','title','pincode','availability','seller','rating','no_of_ratings','no_of_reviews','selling_price','mrp','free_delivery','platform','hour']]
fk_df.head(2)

,date,fsn,title,pincode,availability,seller,rating,no_of_ratings,no_of_reviews,selling_price,mrp,free_delivery,platform,hour
0,2025-09-03,BRAG6WTXHT4YRGMZ,Women Full Coverage Lightly Padded Bra (Black),560001,Instock,JockeyIndia,4.1,500 ratings and 24 reviews,500 ratings and 24 reviews,949,0,None,Flipkart,16
1,2025-09-03,BRAG6WTXSKREGAZX,Women Full Coverage Lightly Padded Bra (Black),560001,Instock,JockeyIndia,4.1,500 ratings and 24 reviews,500 ratings and 24 reviews,949,0,None,Flipkart,16

In [ ]:
fk_df["no_of_ratings"] = fk_df["no_of_ratings"].str.extract(r'(\d+)')
fk_df["no_of_reviews"] = fk_df["no_of_reviews"].str.extract(r'(\d+)\s*reviews')

In [ ]:
# fk_df.head()

,date,fsn,title,pincode,availability,seller,rating,no_of_ratings,no_of_reviews,selling_price,mrp,free_delivery,platform,hour
0,2025-09-03,BRAG6WTXHT4YRGMZ,Women Full Coverage Lightly Padded Bra (Black),560001,Instock,JockeyIndia,4.1,500,24,949,0,None,Flipkart,16
1,2025-09-03,BRAG6WTXSKREGAZX,Women Full Coverage Lightly Padded Bra (Black),560001,Instock,JockeyIndia,4.1,500,24,949,0,None,Flipkart,16
2,2025-09-03,BRAG6WTXQAESWZ96,Women Full Coverage Lightly Padded Bra (Black),560001,Instock,JockeyIndia,4.1,500,24,949,0,None,Flipkart,16
3,2025-09-03,BRAG6WTXVG9N2PGT,Women Full Coverage Lightly Padded Bra (Black),560001,Instock,JockeyIndia,4.1,500,24,979,0,None,Flipkart,16
4,2025-09-03,BRAG6WTXEJJYEC6V,Women Full Coverage Lightly Padded Bra (Black),560001,Instock,JockeyIndia,4.1,500,24,979,0,None,Flipkart,16

In [ ]:
# fk_df['no_of_ratings']=fk_df['no_of_ratings'].str.replace(',','').astype(float)
# fk_df['no_of_reviews']=fk_df['no_of_reviews'].str.replace(',','').astype(float)

In [ ]:
final_df=pd.merge(fk_df,df_,on='fsn',how='left')
final_df.tail(2)

,date,fsn,title,pincode,availability,seller,rating,no_of_ratings,no_of_reviews,selling_price,mrp,free_delivery,platform,hour,account,category,sub_category,sub_category_1,sub_category_2,sub_category_3
248,2025-09-03,BRAG6WTXTDB5NQPA,Women Full Coverage Lightly Padded Bra (Beige),700001,Out of stock,Kukukidukaan4,4.1,500,24,979,0,None,Flipkart,16,Jockey,BRA,Bras,Plus Size Bra,,
249,2025-09-03,TRKFGYFWQBQMTSKQ,PB03 Super Combed Cotton Elastane Stretch Boys...,700001,Out of stock,Kukukidukaan4,4.2,746,62,509,0,None,Flipkart,16,Jockey,JI - IW,trunk,Trunk,,

In [ ]:
from sqlalchemy import create_engine
engine = create_engine('postgresql+psycopg2://postgres:tr0ub4dor&3@nucleus.ckojnefw0d56.us-west-1.rds.amazonaws.com/GIF_2025')
final_df.to_sql('flipkart_buybox', engine, if_exists='append', index=False)

250

In [ ]:
driver.quit()